"""
Liste des pays du monde + systeme educatif associe
Permet a l'ecole de choisir son pays UNE FOIS dans Parametres,
puis le module Bulletins s'adapte automatiquement.
"""

# Systemes educatifs supportes
SYSTEMES = {
    "fr": {
        "label": "Francophone (trimestres, notes /20)",
        "label_periode": "Trimestre",
        "nb_periodes": 3,
        "bareme": "sur20",
        "note_max": 20,
        "note_min": 0,
        "seuil_admission": 10,
        "titre_bulletin": "BULLETIN DE NOTES",
    },
    "en": {
        "label": "Anglophone (terms, grades)",
        "label_periode": "Term",
        "nb_periodes": 3,
        "bareme": "sur100",
        "note_max": 100,
        "note_min": 0,
        "seuil_admission": 50,
        "titre_bulletin": "REPORT CARD",
    },
    "ar": {
        "label": "Arabophone (trimestres, notes /20)",
        "label_periode": "Trimestre",
        "nb_periodes": 3,
        "bareme": "sur20",
        "note_max": 20,
        "note_min": 0,
        "seuil_admission": 10,
        "titre_bulletin": "BULLETIN DE NOTES",
    },
    "pt": {
        "label": "Lusophone (trimestres, notes /20)",
        "label_periode": "Trimestre",
        "nb_periodes": 3,
        "bareme": "sur20",
        "note_max": 20,
        "note_min": 0,
        "seuil_admission": 10,
        "titre_bulletin": "BOLETIM DE NOTAS",
    },
    "es": {
        "label": "Hispanophone (trimestres, notes /10)",
        "label_periode": "Trimestre",
        "nb_periodes": 3,
        "bareme": "sur10",
        "note_max": 10,
        "note_min": 0,
        "seuil_admission": 5,
        "titre_bulletin": "BOLETIN DE NOTAS",
    },
    "autre": {
        "label": "Autre (systeme personnalise)",
        "label_periode": "Periode",
        "nb_periodes": 3,
        "bareme": "sur20",
        "note_max": 20,
        "note_min": 0,
        "seuil_admission": 10,
        "titre_bulletin": "BULLETIN DE NOTES",
    },
}


# ============================================================
# LISTE DES PAYS DU MONDE (par ordre alphabetique)
# Format : (nom, code_iso, systeme_educatif)
# ============================================================
PAYS_MONDE = [
    ("Afghanistan", "AF", "ar"),
    ("Afrique du Sud", "ZA", "en"),
    ("Albanie", "AL", "autre"),
    ("Algerie", "DZ", "ar"),
    ("Allemagne", "DE", "autre"),
    ("Andorre", "AD", "es"),
    ("Angola", "AO", "pt"),
    ("Antigua-et-Barbuda", "AG", "en"),
    ("Arabie Saoudite", "SA", "ar"),
    ("Argentine", "AR", "es"),
    ("Armenie", "AM", "autre"),
    ("Australie", "AU", "en"),
    ("Autriche", "AT", "autre"),
    ("Azerbaidjan", "AZ", "autre"),
    ("Bahamas", "BS", "en"),
    ("Bahrein", "BH", "ar"),
    ("Bangladesh", "BD", "en"),
    ("Barbade", "BB", "en"),
    ("Belgique", "BE", "fr"),
    ("Belize", "BZ", "en"),
    ("Benin", "BJ", "fr"),
    ("Bhoutan", "BT", "en"),
    ("Bielorussie", "BY", "autre"),
    ("Birmanie (Myanmar)", "MM", "en"),
    ("Bolivie", "BO", "es"),
    ("Bosnie-Herzegovine", "BA", "autre"),
    ("Botswana", "BW", "en"),
    ("Bresil", "BR", "pt"),
    ("Brunei", "BN", "en"),
    ("Bulgarie", "BG", "autre"),
    ("Burkina Faso", "BF", "fr"),
    ("Burundi", "BI", "fr"),
    ("Cambodge", "KH", "autre"),
    ("Cameroun", "CM", "fr"),
    ("Canada", "CA", "en"),
    ("Cap-Vert", "CV", "pt"),
    ("Republique Centrafricaine", "CF", "fr"),
    ("Chili", "CL", "es"),
    ("Chine", "CN", "autre"),
    ("Chypre", "CY", "autre"),
    ("Colombie", "CO", "es"),
    ("Comores", "KM", "fr"),
    ("Congo (Brazzaville)", "CG", "fr"),
    ("Congo (RDC)", "CD", "fr"),
    ("Coree du Nord", "KP", "autre"),
    ("Coree du Sud", "KR", "autre"),
    ("Costa Rica", "CR", "es"),
    ("Cote d'Ivoire", "CI", "fr"),
    ("Croatie", "HR", "autre"),
    ("Cuba", "CU", "es"),
    ("Danemark", "DK", "autre"),
    ("Djibouti", "DJ", "fr"),
    ("Dominique", "DM", "en"),
    ("Egypte", "EG", "ar"),
    ("Emirats Arabes Unis", "AE", "ar"),
    ("Equateur", "EC", "es"),
    ("Erythree", "ER", "autre"),
    ("Espagne", "ES", "es"),
    ("Estonie", "EE", "autre"),
    ("Eswatini", "SZ", "en"),
    ("Etats-Unis", "US", "en"),
    ("Ethiopie", "ET", "autre"),
    ("Fidji", "FJ", "en"),
    ("Finlande", "FI", "autre"),
    ("France", "FR", "fr"),
    ("Gabon", "GA", "fr"),
    ("Gambie", "GM", "en"),
    ("Georgie", "GE", "autre"),
    ("Ghana", "GH", "en"),
    ("Grece", "GR", "autre"),
    ("Grenade", "GD", "en"),
    ("Guatemala", "GT", "es"),
    ("Guinee", "GN", "fr"),
    ("Guinee-Bissau", "GW", "pt"),
    ("Guinee Equatoriale", "GQ", "es"),
    ("Guyana", "GY", "en"),
    ("Haiti", "HT", "fr"),
    ("Honduras", "HN", "es"),
    ("Hongrie", "HU", "autre"),
    ("Iles Marshall", "MH", "en"),
    ("Iles Salomon", "SB", "en"),
    ("Inde", "IN", "en"),
    ("Indonesie", "ID", "autre"),
    ("Irak", "IQ", "ar"),
    ("Iran", "IR", "ar"),
    ("Irlande", "IE", "en"),
    ("Islande", "IS", "autre"),
    ("Israel", "IL", "autre"),
    ("Italie", "IT", "autre"),
    ("Jamaique", "JM", "en"),
    ("Japon", "JP", "autre"),
    ("Jordanie", "JO", "ar"),
    ("Kazakhstan", "KZ", "autre"),
    ("Kenya", "KE", "en"),
    ("Kirghizistan", "KG", "autre"),
    ("Kiribati", "KI", "en"),
    ("Koweit", "KW", "ar"),
    ("Laos", "LA", "autre"),
    ("Lesotho", "LS", "en"),
    ("Lettonie", "LV", "autre"),
    ("Liban", "LB", "ar"),
    ("Liberia", "LR", "en"),
    ("Libye", "LY", "ar"),
    ("Liechtenstein", "LI", "autre"),
    ("Lituanie", "LT", "autre"),
    ("Luxembourg", "LU", "fr"),
    ("Macedoine du Nord", "MK", "autre"),
    ("Madagascar", "MG", "fr"),
    ("Malaisie", "MY", "en"),
    ("Malawi", "MW", "en"),
    ("Maldives", "MV", "en"),
    ("Mali", "ML", "fr"),
    ("Malte", "MT", "en"),
    ("Maroc", "MA", "ar"),
    ("Maurice", "MU", "en"),
    ("Mauritanie", "MR", "ar"),
    ("Mexique", "MX", "es"),
    ("Micronesie", "FM", "en"),
    ("Moldavie", "MD", "autre"),
    ("Monaco", "MC", "fr"),
    ("Mongolie", "MN", "autre"),
    ("Montenegro", "ME", "autre"),
    ("Mozambique", "MZ", "pt"),
    ("Namibie", "NA", "en"),
    ("Nauru", "NR", "en"),
    ("Nepal", "NP", "en"),
    ("Nicaragua", "NI", "es"),
    ("Niger", "NE", "fr"),
    ("Nigeria", "NG", "en"),
    ("Norvege", "NO", "autre"),
    ("Nouvelle-Zelande", "NZ", "en"),
    ("Oman", "OM", "ar"),
    ("Ouganda", "UG", "en"),
    ("Ouzbekistan", "UZ", "autre"),
    ("Pakistan", "PK", "en"),
    ("Palaos", "PW", "en"),
    ("Palestine", "PS", "ar"),
    ("Panama", "PA", "es"),
    ("Papouasie-Nouvelle-Guinee", "PG", "en"),
    ("Paraguay", "PY", "es"),
    ("Pays-Bas", "NL", "autre"),
    ("Perou", "PE", "es"),
    ("Philippines", "PH", "en"),
    ("Pologne", "PL", "autre"),
    ("Portugal", "PT", "pt"),
    ("Qatar", "QA", "ar"),
    ("Republique Dominicaine", "DO", "es"),
    ("Republique Tcheque", "CZ", "autre"),
    ("Roumanie", "RO", "autre"),
    ("Royaume-Uni", "GB", "en"),
    ("Russie", "RU", "autre"),
    ("Rwanda", "RW", "fr"),
    ("Saint-Christophe-et-Nieves", "KN", "en"),
    ("Saint-Marin", "SM", "autre"),
    ("Saint-Vincent-et-les-Grenadines", "VC", "en"),
    ("Sainte-Lucie", "LC", "en"),
    ("Salvador", "SV", "es"),
    ("Samoa", "WS", "en"),
    ("Sao Tome-et-Principe", "ST", "pt"),
    ("Senegal", "SN", "fr"),
    ("Serbie", "RS", "autre"),
    ("Seychelles", "SC", "fr"),
    ("Sierra Leone", "SL", "en"),
    ("Singapour", "SG", "en"),
    ("Slovaquie", "SK", "autre"),
    ("Slovenie", "SI", "autre"),
    ("Somalie", "SO", "ar"),
    ("Soudan", "SD", "ar"),
    ("Soudan du Sud", "SS", "en"),
    ("Sri Lanka", "LK", "en"),
    ("Suede", "SE", "autre"),
    ("Suisse", "CH", "fr"),
    ("Suriname", "SR", "autre"),
    ("Syrie", "SY", "ar"),
    ("Tadjikistan", "TJ", "autre"),
    ("Tanzanie", "TZ", "en"),
    ("Tchad", "TD", "fr"),
    ("Thailande", "TH", "autre"),
    ("Timor oriental", "TL", "pt"),
    ("Togo", "TG", "fr"),
    ("Tonga", "TO", "en"),
    ("Trinite-et-Tobago", "TT", "en"),
    ("Tunisie", "TN", "ar"),
    ("Turkmenistan", "TM", "autre"),
    ("Turquie", "TR", "autre"),
    ("Tuvalu", "TV", "en"),
    ("Ukraine", "UA", "autre"),
    ("Uruguay", "UY", "es"),
    ("Vanuatu", "VU", "fr"),
    ("Vatican", "VA", "autre"),
    ("Venezuela", "VE", "es"),
    ("Vietnam", "VN", "autre"),
    ("Yemen", "YE", "ar"),
    ("Zambie", "ZM", "en"),
    ("Zimbabwe", "ZW", "en"),
]


# ============================================================
# FONCTIONS UTILITAIRES
# ============================================================
def lister_pays():
    """Retourne la liste des noms de pays tries alphabetiquement."""
    return sorted([p[0] for p in PAYS_MONDE])


def get_systeme_pour_pays(nom_pays):
    """Retourne la cle du systeme educatif pour un pays donne."""
    if not nom_pays:
        return "autre"
    nom_lower = nom_pays.strip().lower()
    for nom, iso, sys_key in PAYS_MONDE:
        if nom.lower() == nom_lower:
            return sys_key
    return "autre"


def get_config_pour_pays(nom_pays):
    """Retourne la config complete du systeme educatif d'un pays."""
    sys_key = get_systeme_pour_pays(nom_pays)
    return SYSTEMES.get(sys_key, SYSTEMES["autre"])


def get_systeme_label(nom_pays):
    """Retourne le libelle du systeme educatif d'un pays."""
    sys_key = get_systeme_pour_pays(nom_pays)
    return SYSTEMES.get(sys_key, SYSTEMES["autre"])["label"]